login/urls.py
# log/urls.py
from django.conf.urls import url
from . import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

majatek/urls.py
from django.conf.urls.static import  static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from store.views import CreateSt, StListView
from django.contrib.auth import views
from login.forms import LoginForm
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'', include('login.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    #url(r'^create-st/', CreateSt.as_view(), name='create-st'),
    url(r'', include('store.urls')),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import CreateSt, StListView, DelSt, StcListView, ProductsListView, DetailViewSt
from . import views
#from django.contrib.auth import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
url(r'^create-st/', views.add_st, name='create-st'),
url(r'^delete-st/(?P<pk>\d+)/$', DelSt.as_view(), name='delete-st'),
url(r'^detail-view-st/(?P<pk>\d+)/$', login_required(DetailViewSt.as_view(), login_url="/"), name='detail-view-st'),
#url(r'^$', login_required(StListView.as_view(), login_url="login/"), name='list-st'),
url(r'^$', login_required(ProductsListView.as_view(), login_url="login/"), name='products-list'),
url(r'^add-stc/(?P<nr_st>\d+)/$', views.add_stc, name='add-stc'),
#url(r'^add-stc/(?P<pk>\d+)/$', views.add_stc, name='add-stc'),
url(r'^list-stc/', login_required(StcListView.as_view(), login_url="/"), name='list-stc'),
url(r'^ajax/validate_nr_st/$', views.validate_nr_st, name='validate_nr_st'),
url(r'^upload/$', views.upload_file, name='upload-file'),
]

store/models.py
from django.db import models
from django.conf import settings
from datetime import date



class NrSt(models.Model):

	

	owner = models.ForeignKey(settings.AUTH_USER_MODEL)
	nr_st = models.CharField(max_length = 9, unique=True)
	name = models.CharField(max_length = 255)
	data_przyjecia = models.DateField(default=date.today)
	price = models.DecimalField(null = True, blank = True, max_digits = 20, decimal_places = 2)
	uwagi = models.TextField(null = True, blank=True)
	dzierzawca = models.CharField(max_length = 255, null = True, blank=True)
	place = models.CharField(max_length = 255, null = True, blank=True)

	def __str__(self):
		return self.name

class NrStc(models.Model):
	nr_st = models.ForeignKey(NrSt)
	owner = models.ForeignKey(settings.AUTH_USER_MODEL)
	nr_stc = models.CharField(max_length = 9, unique=True)
	name = models.CharField(max_length = 255)
	data_przyjecia = models.DateField(default=date.today)
	price = models.DecimalField(null = True, blank=True, max_digits = 20, decimal_places = 2)
	uwagi = models.TextField(null=True)
	dzierzawca = models.CharField(max_length = 255, null = True)
	place = models.CharField(max_length = 255, null = True, blank = True)
	photo = models.ImageField(null=True)

	def __str__(self):
		return self.name

class Upload(models.Model):
	upload = models.FileField(upload_to='upload/')

store/forms.py
from django import forms
from .models import NrStc, NrSt, Upload
import re


class AddStc(forms.ModelForm):
	#nr_stc = forms.CharField(max_length=9)
	#nazwa = froms.CharField(max_length=255)

	class Meta:
		model = NrStc
		fields = ['nr_stc','name', 'data_przyjecia']
		widgets = {
            'data_przyjecia': forms.DateInput(attrs={'id':'datepicker'}),
            'uwagi': forms.CharField(widget=forms.Textarea),
        }

	


class AddSt(forms.ModelForm):
	class Meta:
		model = NrSt
		fields = ['nr_st', 'name', 'dzierzawca', 'place', 'price', 'data_przyjecia', 'uwagi']
		

		widgets = {
			'data_przyjecia': forms.DateInput(attrs={'id':'datepicker', 'class':'form-control'}),
			'price': forms.NumberInput(attrs={'type':'', 'class':'form-control'}),
			'nr_st': forms.TextInput(attrs={'class':'form-control'}),
			'name': forms.TextInput(attrs={'class':'form-control'}),
			'place': forms.TextInput(attrs={'class':'form-control'}),
			'dzierzawca': forms.TextInput(attrs={'class':'form-control'}),
			'uwagi': forms.Textarea(attrs={'class':'form-control'}),
		}

	def clean_price(self):
		price = self.cleaned_data['price']
		ok = re.match(r'^\d*\.\d{2}$', str(price))
		if not ok:
			raise forms.ValidationError('Podaj miejsca dziesiętne')
		return price

	def clean_nr_st(self):
		nr_st = self.cleaned_data['nr_st']
		if len(nr_st) < 9:
			raise forms.ValidationError('Numer ST jest za krótki!')
		ok = re.match(r'^\d+$', nr_st)
		if not ok:
			raise forms.ValidationError('Pole powinno zawierać tylko cyfry')
		return nr_st

class UploadFileForm(forms.ModelForm):
	class Meta:
		model = Upload
		fields = ['upload']
	#upload = forms.FileField()
	
	

store/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import NrSt, NrStc
from django.urls import reverse_lazy
from .forms import AddStc, AddSt, UploadFileForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .upload import handle_files
import io
from django.conf import settings
from django.core.files.storage import FileSystemStorage

class CreateSt(CreateView):
	template_name = 'store/create-st.html'
	model = NrSt
	fields = ['owner', 'nr_st', 'name']
	success_url = '/'


class StListView(ListView):
	template_name = 'store/list-st.html'
	model = NrSt
	fields = ['owner', 'nr_st', 'name']


class ProductsListView(ListView):
	context_object_name = 'products-list'
	template_name = 'store/products-list.html'
	#queryset = NrSt.objects.
	def get_queryset(self):
		return NrSt.objects.filter(owner = self.request.user)

	def get_context_data(self, **kwargs):
		context = super(ProductsListView, self).get_context_data(**kwargs)
		context['numer_stc'] = NrStc.objects.all()
		return context
	

class StcListView(ListView):
	template_name = 'store/list-stc.html'
	model = NrStc
	fields = ['owner', 'nr_st', 'name', 'nr_stc', 'data_przyjecia']

class DetailViewSt(DetailView):
	model = NrSt
	template_name = 'store/detail-view-st.html'

class DelSt(DeleteView):
	template_name = 'store/delete-st.html'
	model = NrSt
	success_url = reverse_lazy('products-list')

'''class CreateStc(CreateView):
	model = NrStc
	template_name = 'store/create-stc.html'
	fields = ['nr_stc', 'name']
	'''
def add_stc(request, nr_st):

	if request.method == 'POST':
		form = AddStc(request.POST)
		if form.is_valid():
			stc = form.save(commit = False)
			stc.owner = request.user
			#stc.nr_st = request.NrSt.objects.filter(nr_st=pk)
			stc.nr_st = get_object_or_404(NrSt, nr_st = nr_st)
			stc.save()


	form = AddStc
	return render(request, 'store/create-stc.html', {'form':form})

def add_st(request):
	form = AddSt()
	if request.method == 'POST':
		form = AddSt(request.POST)
		if form.is_valid():
			st = form.save(commit = False)
			st.owner = request.user
			st.save()
			return HttpResponseRedirect('/')
	#form = AddSt()
	return render(request, 'store/create-st.html', {'form':form})

def validate_nr_st(request):
	nr_st = request.GET.get('nr_st', None)
	data = {
		'is_taken': NrSt.objects.filter(nr_st__iexact=nr_st).exists()
	}
	if data['is_taken']:
			data['error_message'] = 'Podany przez Ciebie numer St już istnieje w bazie!'
	return JsonResponse(data)

def upload_file(request):
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			myfile = request.FILES['upload']
			fs = FileSystemStorage()
			filename = fs.save(myfile.name, myfile)
			uploaded_file_url = fs.url(filename)
			handle_files(settings.MEDIA_ROOT+'/'+str(myfile))
			return HttpResponseRedirect('/success/')
	else:
		form = UploadFileForm()
	return render (request, 'store/upload.html', {'form':form })

store/templates/store/create-st.html
{% extends "base.html"  %}
{% comment %}
{% block 'content' %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_ul}}
    <input type="submit" value="Save" />
</form>
{% endblock %}
{% endcomment %}
{% block javascript %}
   <script>
 /*$("#id_nr_st").change(function () {
      var nr_st = $(this).val();

      $.ajax({
        url: '/ajax/validate_nr_st/',
        data: {
          'nr_st': nr_st
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert("Numer St podany przez Ciebie już intieje!.");
          }
        }
      });

    });*/

 $("#id_nr_st").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-username-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
            $("#id_nr_st").val('');
          }
        }
      });

    });
/*------------------------------------------------------------*/

   $( document ).ready( function(){
    $( function() {

    $( '#datepicker' ).datepicker({ datepicker: true, dateFormat: 'dd.mm.yy', changeYear: true, monthNames: [ "Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień" ] });
                } );
}); ( jQuery );

  </script>
   {% endblock%}
 

{% block 'content' %}
 
  <style >
      li{color:red;}
  </style>
    <div class="col-lg-7">
    <form  method="POST" data-validate-username-url = "{% url 'validate_nr_st' %}" class="form-horizontal">{% csrf_token %}
     <fieldset>
    <legend>Dodaj składnik - ST</legend>
    <div class="form-group">
       {{ form.nr_st.errors }}
      <label  class="col-lg-2 control-label">Nr. ST:</label>
      <div class="col-lg-10">{{ form.nr_st }}</div>
      <label  class="col-lg-2 control-label">Nazwa:</label>
      <div class="col-lg-10">{{ form.name }}</div>
      {{ form.price.errors }}
      <label  class="col-lg-2 control-label">Cena:</label>

      <div class="col-lg-10">{{ form.price }} </div>
      <label  class="col-lg-2 control-label">Data:</label>
      <div class="col-lg-10">{{ form.data_przyjecia }}</div>
      <label  class="col-lg-2 control-label">Użytkownik:</label>
      <div class="col-lg-10">{{ form.dzierzawca }}</div>
      <label  class="col-lg-2 control-label">Miejsce:</label>
      <div class="col-lg-10">{{ form.place }}</div>
      <label  class="col-lg-2 control-label">Uwagi:</label>
      <div class="col-lg-10">{{ form.uwagi }}</div>
    </div>
  <div class="form-group">
      <div class="col-lg-10">
      <button type="submit" class="btn btn-primary col-lg-offset-3">Zapisz</button>
        <button type="reset" class="btn btn-default">Wyczyść</button>
        <button type="reset" class="btn btn-default" onclick="location.href='/'">Anuluj</button>
        
      </div>
    </div>
      
        </fieldset>
    </form>
    </div>
    <div class="col-lg-5"></div> 
{% endblock %}

store/templates/store/create-stc.html
{% extends 'base.html' %}

{% block 'content' %}
    <h1>Dodaj STC</h1>
    <form method="POST" class="post-form">{% csrf_token %}
    	<table>
        <tr><td>Nazwa:</td><td> {{ form.name }}</td></tr>
        <tr><td>Nr. STC:</td><td> {{ form.nr_stc}}</td></tr>
        <tr><td>Data:</td><td> {{ form.data_przyjecia}}</td></tr>
        </table>
        <button type="submit" class="save btn btn-default">Dadaj</button>
    </form>
   {% block javascript %}
   <script>
   $( document ).ready( function(){
    $( function() {

    $( '#datepicker' ).datepicker({ datepicker: true, dateFormat: 'dd.mm.yy' });
				} );
}); ( jQuery );

  </script>
   {% endblock%}
{% endblock %}

store/templates/store/delete-st.html
{% extends "base.html"  %}
{% block 'content' %}
<form action="" method="post">{% csrf_token %}
    <h3>Czy na pewno chcesz usunąć składnik <strong>{{object.name}}</strong> o nr. ST-{{ object.nr_st }}?</h3>
    <input type="submit" value="Usuń" />
    <input type="button" value="Anuluj" onClick="javascript:history.go(-1);" />
</form>
{% endblock %}

store/templates/store/detail-view-st.html
{% extends "base.html"  %}

{% block 'content' %}
<h3>Składnik {{ object.name }} o numerze ST-{{ object.nr_st }}</h3>
<table class="table">
<tr><td>Data przyjęcia</td><td>{{ object.data_przyjecia }}</td></tr>
<tr><td>Cena:</td><td>{{ object.price }} zł</td></tr>
<tr><td>Miejsce:</td><td>{{ object.place }}</td></tr>
<tr><td>Użytkownik:</td><td>{{ object.dzierzawca }}</td></tr>
<tr><td>Uwagi:</td><td>{{ object.uwagi }}</td></tr>
</table>
<button type="" class="btn btn-default" onclick="location.href='/'">Wróć</button>
{% endblock %}

store/templates/store/list-st.html
{% extends "base.html"  %}
{% block 'content' %}
<table class="table table-striped table-hover">
<thead>
	<tr><th>Lp.</th><th>Nr. ST</th><th>Nazwa</th><th></th></tr>
</thead>

{% for st in object_list %}
{% if user.pk == st.owner.pk %}
<tr><td>{{ cycle }}</td><td> ST-{{ st.nr_st }}</td><td> {{ st.name }}</td><td><div class="btn-group">
  <a href="#" class="btn btn-default">Akcja</a>
  <a aria-expanded="false" href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#">Podląd</a></li>
    <li><a href="#">Edytuj</a></li>
    <li><a href="{% url 'delete-st' pk=st.id %}">Usuń</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'add-stc' nr_st=st.nr_st %}">Dodaj STC</a></li>
  </ul>
</div></td></tr>

{% endif %}
{% endfor %}
</table>
<a href="{% url 'create-st' %}" class="btn btn-default">Dodaj ST</a>
{% endblock %}

store/templates/store/list-stc.html
{% extends "base.html"  %}
{% block 'content' %}
 <table class="table table-striped table-hover">
{% for stc in object_list %}

    <tr><td>{{ stc.nr_st.nr_st }}</td><td> {{ stc.nr_stc }}</td><td> {{ stc.name }}</td> <td>{{ stc.data_przyjecia }}</td></tr>
 

{% endfor %}
</table>
{% endblock  %}

store/templates/store/products-list.html
{% extends "base.html"  %}
{% block 'content' %}
<table class="table table-striped table-hover">
<thead>

	<tr><th>Lp.</th><th>Nr. ST</th><th>Nazwa</th><th></th></tr>
</thead>

{% for st in object_list %}



<tr><td></td><td> ST-{{ st.nr_st }}</td><td> {{ st.name }}</td><td><div class="btn-group">

  <a href="#" class="btn btn-default">Akcja</a>
  <a aria-expanded="false" href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'detail-view-st' pk=st.id %}">Podląd</a></li>
    <li><a href="#">Edytuj</a></li>
    <li><a href="{% url 'delete-st' pk=st.id %}">Usuń</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'add-stc' nr_st=st.nr_st %}">Dodaj STC</a></li>
  </ul>
</div></td></tr>

{% for stc in numer_stc %}
{%if stc.nr_st == st %}
<tr style="background-color:rgb(101, 110, 65);"><td></td><td>&nbsp;&nbsp;&nbsp;STC/{{stc.nr_stc}}</td><td>&nbsp;&nbsp;&nbsp;{{stc.name}}</td><td></td></tr>
{%endif%}
{%endfor%}




{% endfor %}
</table>
{% endblock %}

store/templates/store/upload.html
{% extends "base.html"  %}

{% block 'content' %}
 
    <form  method="POST" enctype="multipart/form-data" class="form-horizontal" >{% csrf_token %}
     <fieldset>
    <legend>Dodaj składnik - ST</legend>
    <div class="form-group">
 
      <label  class="col-lg-2 control-label">Upload:</label>
      <div class="col-lg-10">{{ form.upload }}</div>
    </div>
  <div class="form-group">
      <div class="col-lg-10">
      <button type="submit" class="btn btn-primary col-lg-offset-3">Zapisz</button>
        <button type="reset" class="btn btn-default">Wyczyść</button>
        <button type="reset" class="btn btn-default" onclick="location.href='/'">Anuluj</button>
        
      </div>
    </div>
      
        </fieldset>
    </form>
    </div>
    <div class="col-lg-5"></div> 
{% endblock %}